# SwiftLint Configuration for FocusPal

# Excluded paths
excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData

# Disabled rules
disabled_rules:
  - todo  # Allow TODO comments in codebase

# Rule configurations
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length:
    warning: 1  # Allow single-character names like 'i' for loops
  excluded:
    - i
    - id
    - x
    - y

large_tuple:
  warning: 3
  error: 4

# Opt-in rules
opt_in_rules:
  - empty_count
  - closure_spacing

# Nested configurations for test files
included:
  - FocusPal
  - FocusPalTests
  - FocusPalUITests
