# SwiftLint Configuration for FocusPal

# Excluded paths
excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData

# Disabled rules
disabled_rules:
  - todo  # Allow TODO comments in codebase
  - inclusive_language  # Allow existing variable names
  - for_where  # Allow if inside for loops
  - redundant_string_enum_value  # Allow explicit enum values
  - multiple_closures_with_trailing_closure  # Allow trailing closures
  - redundant_discardable_let  # Allow let _ = pattern
  - unused_optional_binding  # Allow let _ = for optionals
  - trailing_newline  # Don't enforce trailing newlines
  - unused_closure_parameter  # Allow unused closure parameters
  - empty_count  # Allow count == 0 checks
  - implicit_optional_initialization  # Allow explicit nil initialization
  - non_optional_string_data_conversion  # Allow optional Data conversion

# Rule configurations
file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true

type_body_length:
  warning: 800
  error: 1000

function_body_length:
  warning: 150
  error: 250

line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length:
    warning: 1  # Allow single-character names like 'i' for loops
  excluded:
    - i
    - id
    - x
    - y

large_tuple:
  warning: 4
  error: 6

# Opt-in rules
opt_in_rules:
  - empty_count
  - closure_spacing

# Nested configurations for test files
included:
  - FocusPal
  - FocusPalTests
  - FocusPalUITests
