name: FocusPal
options:
  bundleIdPrefix: com.focuspal
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  FocusPal:
    type: application
    platform: iOS
    sources:
      - path: FocusPal
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.focuspal.dev
        INFOPLIST_KEY_CFBundleDisplayName: FocusPal
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_VERSION: 5.0
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: FocusPal/Info.plist
      properties:
        UILaunchScreen: {}

  FocusPalTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FocusPalTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.focuspal.dev.tests
    dependencies:
      - target: FocusPal

  FocusPalUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: FocusPalUITests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.focuspal.dev.uitests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.0
    dependencies:
      - target: FocusPal

schemes:
  FocusPal:
    build:
      targets:
        FocusPal: all
        FocusPalTests: [test]
        FocusPalUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - FocusPalTests
        - FocusPalUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
